# Generated by Django 3.0 on 2024-08-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_code', models.CharField(max_length=10)),
                ('element_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_code', models.CharField(max_length=10)),
                ('menu_name', models.TextField(max_length=50)),
            ],
        ),
    ]
