# Generated by Django 4.0.10 on 2024-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0002_alter_ordermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="eng_name",
            field=models.CharField(max_length=200, verbose_name="English name"),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="jap_name",
            field=models.CharField(max_length=200, verbose_name="Japanese name"),
        ),
    ]
